<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/didactica_ciencia_datos/blob/main/propuesta/unidad_didac/1_statistic/1_Basic_Descriptive_Statistics/2_medidas_variabilidad/1_rango.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

## [Video de apoyo a la lectura interactiva y experimental de esta cuaderno](https://www.youtube.com/watch?v=aI8bZ3j5qk4)

# Rango

Defnición: Diferencia entre el valor máximo y el valor mímo. 

# Agenda

1. Generación de muestras o matrices aleatorias con el módulo random de NumPy. 
2. rango como función definida por el usuario
3. rango con statistics
4. Rango intercuartílico `scipy.stats.iqr()`

# Práctica de generación de matrices de números aleatorios

## La función `numpy.random. rand()`

In [8]:
import numpy as np 

from numpy import random as r



In [12]:
datos = r.rand(2,3)

In [13]:
print(datos) 

[[0.39576398 0.33395187 0.27466362]
 [0.98224166 0.88376511 0.41966874]]


In [43]:
0.982-0.395

0.587

## Práctica de cálculo e interpretación del rango con Python

In [14]:
import numpy as np 
import scipy as sc
import statistics as st 

In [48]:
def calcula_rango_por_columnas(datos):
    maximo = np.max(datos, axis = 0)  #con axis = 0 toma los maximos por columna. 
    minimo = np.min(datos, axis = 0)
    rango_por_columnas = maximo-minimo 
    return rango_por_columnas 

In [49]:
calcula_rango_por_columnas(datos) 

array([0.58647768, 0.54981324, 0.14500512])

# Calculo de el rango con el módulo statistics de Python

In [22]:
st.quantiles(datos, n=2, method='exclusive', axis = 0)

TypeError: quantiles() got an unexpected keyword argument 'axis'

In [ ]:
 Decile cut points for empirically sampled data

In [28]:
data = [105, 129, 87, 86, 111, 111, 89, 81, 108, 92, 110, 100, 75, 105, 103, 109, 76, 119, 99, 91, 103, 129,

        106, 101, 84, 111, 74, 87, 86, 103, 103, 106, 86, 111, 75, 87, 102, 121, 111, 88, 89, 101, 106, 95,

        103, 107, 101, 81, 109, 104]

from statistics import quantiles 

[round(q, 1) for q in quantiles(data, n=2)]


[102.5]

In [29]:
data.sort()

In [30]:
data 

[74,
 75,
 75,
 76,
 81,
 81,
 84,
 86,
 86,
 86,
 87,
 87,
 87,
 88,
 89,
 89,
 91,
 92,
 95,
 99,
 100,
 101,
 101,
 101,
 102,
 103,
 103,
 103,
 103,
 103,
 104,
 105,
 105,
 106,
 106,
 106,
 107,
 108,
 109,
 109,
 110,
 111,
 111,
 111,
 111,
 111,
 119,
 121,
 129,
 129]

In [31]:
len(data) 

50

In [36]:
primer_datos_central = 50/2 - 1

segundo_dato_central = 50/2 + 1

In [39]:
(data[int(primer_datos_central)] + data[int(segundo_dato_central)])/2

102.5

# Cálculo del rango con el la función iqr() del módulo stats de la libretría scipy

Compute the interquartile range of the data along the specified axis.

The interquartile range (IQR) is the difference between the 75th and 25th percentile of the data. It is a measure of the dispersion similar to standard deviation or variance, but is much more robust against outliers [2].

The rng parameter allows this function to compute other percentile ranges than the actual IQR. For example, setting rng=(0, 100) is equivalent to numpy.ptp.

The IQR of an empty array is np.nan.

In [40]:
from scipy import stats

In [51]:
stats.iqr(datos, axis = 1, rng=(0,100) ) # con axis = 0 calcula el rango por columnas

array([0.12110036, 0.56257293])

## Ejemplo de calculo de rango con uno datos de estaturas

In [5]:
estaturas = np.array([1.65, 1.55, 1.70, 1.60, 1.65])

In [6]:
estaturas.sort() 

In [7]:
estaturas # estaturas ordenadas

array([1.55, 1.6 , 1.65, 1.65, 1.7 ])

In [6]:
def rango(datos):
    maximo = np.max(datos)
    minimo = np.min(datos)
    rango = maximo-minimo
    return rango 

In [7]:
rango(estaturas) 

0.1499999999999999

In [8]:
sc.stats.iqr(estaturas, rng=(0, 100))  

0.1499999999999999

## Interpretación

Las alturas de las personas dadas solo difieren en 15 centímetros a lo sumo. 

## Tareas de fijación de conceptos y adquisición de habilidades

1. Cree una matriz de orden 2x3 de números aleatorios que distribuyan uniforme en el intervalo $[0,1]$
2. Calcule el rango por filas

## Evaluación

Cree una función de usuario que calcule el rango por columnas o por filas, de acuerdo a como lo pida el ususario. 

## Referentes

* Documentación de scipy para calcular el rango intercuartílico. 
* Función iqr del módulo stats de la librería scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.iqr.html
* Sobre el módulo statistics de python y las medidas de dispersión de datos: https://docs.python.org/es/3/library/statistics.html

## [continue con su formación con el concepto de varianza](https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/1_statistic/1_Basic_Descriptive_Statistics/2_medidas_variabilidad/2_varianza.ipynb)