# La librería NumPy de Python y su estructura de datos insignia que es el nbarray

In [1]:
import numpy as np 

## Crear estructuras de datos con numpy

In [3]:
estaturas_list = [1.65, 1.70, 1.75, 1.64, 1.60]

In [4]:
edades_list = [48, 21, 21, 21, 24]

In [6]:
len(estaturas_list) == len(edades_list) 

True

In [7]:
estaturas_array = np.array(estaturas_list)

In [8]:
edades_array = np.array(edades_list) 

In [9]:
type(estaturas_list)

list

In [10]:
type(estaturas_array)

numpy.ndarray

# La dimensión de los array 

In [11]:
estaturas_array.ndim

1

In [12]:
edades_array.ndim

1

# Acceder a la información de una array

In [18]:
estaturas_array[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [20]:
estaturas_array[-1] # así, con el -1 accedes al ultimo dato

1.6

In [21]:
estaturas_array[-2]

1.64

In [22]:
for edad in edades_array:
    print(edad)

48
21
21
21
24


In [23]:
for i in range(5):
    print(edades_array[-i-1])

24
21
21
21
48


# crear tablas con NumPy

In [24]:
tabla = np.array([edades_list, estaturas_list]) # se crean a través de la función np.array() evaluada en listas de python

In [25]:
tabla 

array([[48.  , 21.  , 21.  , 21.  , 24.  ],
       [ 1.65,  1.7 ,  1.75,  1.64,  1.6 ]])

#  Calcular la dimensión de tu arreglo

In [26]:
tabla.ndim

2

# Acceso a los datos en una matriz o tabla dos dimensional

`tabla[<fila>,<columna>]`


In [27]:
tabla[0,0]

48.0

In [28]:
tabla[1,2]

1.75

# Cómo accedes a filas de una array dos dimensional o tabla

In [29]:
tabla[0,:]

array([48., 21., 21., 21., 24.])

In [30]:
tabla[1, :]

array([1.65, 1.7 , 1.75, 1.64, 1.6 ])

# Cómo accedes a columnas de una array dos dimensional o tabla

In [31]:
tabla[:,0] # primera columna

array([48.  ,  1.65])

In [32]:
tabla

array([[48.  , 21.  , 21.  , 21.  , 24.  ],
       [ 1.65,  1.7 ,  1.75,  1.64,  1.6 ]])

In [34]:
tabla[:,1] # obtuvimos la segunda columna

array([21. ,  1.7])

# Crear un DataFrame

In [35]:
import pandas as pd

In [36]:
dic = {"edades":edades_list, 'estaturas':estaturas_list}

In [37]:
dic['edades']

[48, 21, 21, 21, 24]

In [38]:
dic['estaturas']

[1.65, 1.7, 1.75, 1.64, 1.6]

In [39]:
dic

{'edades': [48, 21, 21, 21, 24], 'estaturas': [1.65, 1.7, 1.75, 1.64, 1.6]}

In [40]:
df = pd.DataFrame(dic) 

In [41]:
df 

,edades,estaturas
0,48,1.65
1,21,1.70
2,21,1.75
3,21,1.64
4,24,1.60


In [42]:
df.edades

0    48
1    21
2    21
3    21
4    24
Name: edades, dtype: int64

In [44]:
df.estaturas # notación de puntos con los dataframe

0    1.65
1    1.70
2    1.75
3    1.64
4    1.60
Name: estaturas, dtype: float64