# Numpy 

Numpy es una biblioteca matemática para python. 

Nos permite hacer computación de manera eficiente y efectiva. 

Es mejor que Python normal debido a sus increíbles capacidades.

En este artículo, solo voy a presentarle los conceptos básicos de lo que se requiere principalmente para el aprendizaje automático y la ciencia de datos. 

No voy a cubrir todo lo que es posible con numpy library. Esta es la primera parte de la serie de tutoriales numpy.

Lo primero que quiero presentarte es la forma en que lo importas.

In [1]:
import numpy as np

Vamos a crear la matriz python y la matriz np.

In [2]:
# python array
a = [1,2,3,4,5,6,7,8,9]
# numpy array
A = np.array([1,2,3,4,5,6,7,8,9])

Si tuviera que imprimirlos, no vería mucha diferencia.

In [3]:
print(a)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


De acuerdo, pero ¿por qué tengo que usar una matriz np en lugar de una matriz normal?
La respuesta es que las matrices np son mejores en términos de computación más rápida y facilidad de manipulación.

## np.arange()

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Lo que hace `arange([start],stop,[step])` es que organiza los números desde que comienzan hasta que se detienen, en pasos de paso. Esto es lo que significa para np.arange(0,10,2):
devuelve una lista np a partir de 0 hasta 10, pero no incluyas 10 e incremente los números por 2 cada vez.
Entonces, así es como obtenemos:

lo importante que recuerde aquí es que el número de parada no se incluirá en la lista.

otro ejemplo:

In [5]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

Antes de continuar, tendré que advertirle que esta "matriz" se llama indistintamente "matriz" o también "vector". Así que no te asustes cuando digo, por ejemplo, "La forma de la matriz es 2 X 3". Todo lo que significa es que la matriz se ve algo como esto:

In [7]:
np.array([[ 2,  7, 12,], 
      [17, 22, 27]])

array([[ 2,  7, 12],
       [17, 22, 27]])

Ahora, hablemos de la forma de una matriz np predeterminada.
Shape es un atributo para la matriz np. Cuando una matriz predeterminada, digamos por ejemplo A se llama con forma, así es como se ve.