# numpy.random.randint

[randint](https://numpy.org/devdocs/reference/random/generated/numpy.random.randint.html)

random.randint(low, high=None, size=None, dtype=int)  

Return random integers from low (inclusive) to high (exclusive).

Devuelve enteros aleatorios de bajo (incluido) a alto (exclusivo).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval $[\text{low}, \text{high})$. If high is None (the default), then results are from $[0, \text{low})$. 

## Note

New code should use the integers method of a ``default_rng()`` instance instead; please see the Quick Start.

## Parameters  

lowint or array-like of ints
Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

highint or array-like of ints, optional
If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional
Desired dtype of the result. Byteorder must be native. The default value is int.

New in version 1.11.0.

## Returns  

outint or ndarray of ints
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

## See also

random_integers
similar to randint, only for the closed interval [low, high], and 1 is the lowest value if high is omitted.

Generator.integers
which should be used for new code.

## Examples

In [2]:
import numpy as np 

In [4]:
np.random.randint(2, size=10)

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [5]:
np.random.randint(1, size=10)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Genere una matriz $2 \times 4$ de entradas enteras no negativas entre 0 y 4, inclusive:

In [6]:
np.random.randint(5, size=(2, 4))

array([[2, 1, 0, 1],
       [0, 0, 0, 2]])

Genere una matriz $1 \times 3$ con 3 límites superiores diferentes

In [11]:
np.random.randint(1, [3, 5, 10]) 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'