# La matriz de correlación 

[numpy.triu](https://numpy.org/doc/stable/reference/generated/numpy.triu.html)

`numpy.triu(m, k=0)`

Triángulo superior de una matriz.

Devuelve una copia de una matriz con los elementos debajo de la k-ésima diagonal en cero.

Consulte la documentación de tril para obtener más detalles.

In [3]:
import numpy as np 
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) 
A 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.triu(A, 0) # ojo con el parámetro de la k - ésima diagonal 


array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [10]:
B = np.ones_like(A, dtype=bool)

In [11]:
np.triu(B) 

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True],
       [False, False, False]])